---
title: "task3_galaxy_PCA"
output: html_notebook
---

```{r}
samsung <- read.csv("galaxy_smallmatrix_labeled_9d.csv")

```

```{r}
# convert variable types, categorical
samsung$galaxysentiment <- as.factor(samsung$galaxysentiment)
```


Train and Test Set: 
```{r}
# Create Train and Test Set for samsung
# create 75% sample of row indices
in_training <-createDataPartition(samsung$galaxysentiment, p = .7, list = FALSE)
# create 75% sample of data and save it to trainData
trainData_samsung <- samsung[in_training, ]
 # create 25% sample of data and save it to test_data
testData_samsung <- samsung[-in_training, ]
# verify split percentages
nrow(trainData_samsung) / nrow(samsung)
```

```{r}
# data = training and testing from iphoneDF (no feature selection) 
# create object containing centered, scaled PCA components from training set
# excluded the dependent variable and set threshold to .95
preprocessParams <- preProcess(trainData_samsung[,-59], method=c("center", "scale", "pca"), thresh = 0.95)
print(preprocessParams)
```


```{r}
# use predict to apply pca parameters, create training, exclude dependant
train.pca <- predict(preprocessParams, trainData_samsung[,-59])

# add the dependent to training
train.pca$galaxysentiment <- trainData_samsung$galaxysentiment

# use predict to apply pca parameters, create testing, exclude dependant
test.pca <- predict(preprocessParams, testData_samsung[,-59])

# add the dependent to training
test.pca$galaxysentiment <- testData_samsung$galaxysentiment

# inspect results
str(train.pca)
str(test.pca)
```



```{r}
#c5
c5_samsung_PCA<- train(galaxysentiment ~., data = train.pca, method = "C5.0",trControl = fitControl)
```

Compare Accuracy on Prediction Results:

```{r}
#c5
prediction_c5_samsung_PCA<- predict(c5_iphone_smallMatrix_PCA, test.pca)
postResample(prediction_c5_iphone_smallMatrix_PCA, test.pca$galaxysentiment)
```


```{r}
summary(c5_iphone_smallMatrix_PCA)
```
